language: python

# command to set services
services:
  - postgresql

# commant to set databse
before_script:
  - psql -c 'create database test_db;' -U postgres
  - psql -c "create user tdd with encrypted password 'tdd';" -U postgres 
  - psql -c 'grant all privileges on database test_db to tdd;' -U postgres

# command to set variables
env: 
  global:
    - DB_NAME: test_db
    - USER_TDB: tdd
    - PASS_TDB: tdd
  
python:
  - "3.7"
  - "3.6"

# command to install dependencies
install:
  - pip install poetry
  - poetry install 

# command to run tests
script: 
  - poetry run python tassi/database/model.py
  - poetry run poe test

after_success:
  - bash <(curl -s https://codecov.io/bash)